# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DriftwoodHandily_iOS' do

  # Pods for DriftwoodHandily_iOS
  pod 'DriftwoodHandily', :path => '../../'

end
